### ISSUE TITLE
Improve order in content_view_version_cleanup 

### ISSUE THREAD

**Issue by lucab85** [RedHatSatellite/satellite-ansible-collection#30]
##### SUMMARY
Improve order in role `redhat.satellite.content_view_version_cleanup` when `satellite_content_view_version_cleanup_keep` parameter is specified.

##### ISSUE TYPE
 - Feature Idea

##### MORE DETAILS
Reproducer of role `redhat.satellite.content_view_version_cleanup` with `satellite_content_view_version_cleanup_keep: 2` parameter:
```
  roles:
    - role: redhat.satellite.content_view_version_cleanup
      vars:
        satellite_server_url:  "https://{{ satellite_server_url }}:443"
        satellite_username: "{{ satellite_user }}"
        satellite_password: "{{ satellite_password }}"
        satellite_organization: "{{ satellite_organization }}"
        satellite_validate_certs: "{{satellite_validate_certs: }}"
        satellite_content_view_version_cleanup_keep: 2
        satellite_content_view_version_cleanup_search: "{{ satellite_search }}"
```
Output:
```
Versions:
 1) ID:        302
    Version:   11.0                             <<<--- currently active and promoted version
    Published: 2020/08/07 13:49:54
 2) ID:        135                                <<<--- why is this version deleted first even though it's the second most recent version
    Version:   5.0
    Published: 2020/02/17 17:34:10
 3) ID:        58
    Version:   1.0
    Published: 2019/12/24 09:31:31
 4) ID:        74
    Version:   2.0
    Published: 2020/01/01 04:07:52
 5) ID:        88
    Version:   3.0
    Published: 2020/01/06 11:30:39
 6) ID:        104                              <<<--- why is this version kept even if it's older than ID 135?
    Version:   4.0
    Published: 2020/02/01 04:05:06~Versions:
 1) ID:        302
    Version:   11.0                             <<<--- currently active and promoted version
    Published: 2020/08/07 13:49:54
 2) ID:        135                                <<<--- why is this version deleted first even though it's the second most recent version
    Version:   5.0
    Published: 2020/02/17 17:34:10
 3) ID:        58
    Version:   1.0
    Published: 2019/12/24 09:31:31
 4) ID:        74
    Version:   2.0
    Published: 2020/01/01 04:07:52
 5) ID:        88
    Version:   3.0
    Published: 2020/01/06 11:30:39
 6) ID:        104                              <<<--- why is this version kept even if it's older than ID 135?
    Version:   4.0
    Published: 2020/02/01 04:05:06~

```
