### ISSUE TITLE
activation_key content_overrides 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by scorpio2k2** [RedHatSatellite/satellite-ansible-collection#35]
When I create activation keys and I add overrides task fails with the following error: 

Error while performing content_override on activation_keys: 400 Client Error: Bad Request for url: https://satellite.domain.com/katello/api/activation_keys/476/content_override

Satellite version 6.8

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.11.1]
  config file = /Users/valentic/.ansible.cfg
  configured module search path = ['/Users/valentic/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/valentic/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jun 29 2021, 05:25:02) [Clang 12.0.5 (clang-1205.0.22.9)]
```

##### COLLECTION VERSION
```
Collection        Version
----------------- -------
redhat.satellite  2.2.0
```

##### STEPS TO REPRODUCE
Task in my role is: 
```yaml
- name: 'Create Activation Keys and attach subscriptions'
  redhat.satellite.activation_key:
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    server_url: "{{ sat_server_url }}"
    validate_certs: no
    organization: "{{ organization_name }}"
    name: "{{ item.name }}"
    lifecycle_environment: "{{ item.lifecycle_environment | default('Library') }}"
    content_view: "{{ item.content_view | default('Default Organization View') }}"
    content_overrides: "{{ item.content_overrides | default(omit) }}"
    subscriptions: "{{ item.subscriptions | default(omit) }}"
    release_version: "{{ item.release_version | default(omit) }}"
    auto_attach: yes
    unlimited_hosts: yes
    state: present
  with_items:
    - "{{ sat_activation_keys }}"
```
Variables
```yaml

sat_activation_keys:
  - name: "{{ organization_label }}_dvl_rhel6"
    lifecycle_environment: "dvl"
    content_view: "{{ organization_label }}"
    release_version: 6Server
    subscriptions:
      - name: custom_el
      - name: custom_el6
      - name: Red Hat Satellite - Add-Ons for Providers
      - name: security
    content_overrides:
      - label: "{{ organization_label }}_security_security_rhel6"
        override: disabled
      - label: satellite-tools-6.8-for-rhel-6-x86_64-rpms
        override: enabled
````

##### ACTUAL RESULTS
```
failed: [localhost] performing content_override on activation_keys: 400 Client Error: Bad Request for url: https://satellite......../katello/api/activation_keys/476/content_override"}
```
